global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "maestrio-dashboard"
    metrics_path: "/api/metrics"
    scheme: "${METRICS_SCHEME}"
    authorization:
      credentials: "${METRICS_SECRET}"
    static_configs:
      - targets: ["${DASHBOARD_HOST}"]
        labels:
          service: "maestrio-dashboard"
